#!/usr/bin/env python3

from enert import *
import sys

tmp_one_task_file = File("tmp_one_task.yml")

def help():
    """
Usage: chikuwansible-task [TASK_FILE_NAME...]
    """
    print(help.__doc__)

def execute_task(task_name):
    if task_name[-4:] == ".yml":
        task_name = task_name[:-4]
    if task_name[:6] == "tasks/":
        task_name = task_name[6:]
    Shell(f"cp -a yml_template.yml {tmp_one_task_file.name}").call()
    s = f"    - include: tasks/{task_name}.yml\n"
    tmp_one_task_file.add(s)
    Shell(f"./chikuwansible-playbook {tmp_one_task_file.name}").call()

argv = sys.argv
argc = len(argv)

if argv[1] in ("-h", "--help"):
    help()
    exit()

for task_name in argv[1:]:
    execute_task(task_name)

tmp_one_task_file.rm()
File(tmp_one_task_file.name[:-4] + ".retry").rm()
