- hosts: localhost
  become: yes
  connection: local
  tasks:
    - include_vars: vars/editable.yml
    - include_vars: vars/uneditable.yml
    - include: tasks/my_python_scripts.yml
    - include: tasks/install_pyenv.yml
    - include: tasks/install_pyenv_versions.yml
    - include: tasks/install_pipenv.yml
    - include: tasks/install_latest_golang.yml
    - include: tasks/install_rust.yml
    - include: tasks/install_exa.yml
    - include: tasks/install_rusgit.yml
    - include: tasks/install_neovim.yml
    - include: tasks/copy_sudoers.yml
