- hosts: localhost
  connection: local
  tasks:
    - include_vars: vars/uneditable.yml
    - include_vars: vars/editable.yml
    - import_tasks:
        file: tasks/install_rust.yml
    - import_tasks:
        file: tasks/install_golang.yml
    - import_tasks:
        file: tasks/install_exa.yml
    - import_tasks:
        file: tasks/install_ripgrep.yml
    - import_tasks:
        file: tasks/install_rusgit.yml
    - import_tasks:
        file: tasks/install_fd.yml
    - import_tasks:
        file: tasks/install_lf.yml
    - import_tasks:
        file: tasks/install_ghq.yml
    - import_tasks:
        file: tasks/install_fzf2nd.yml
    - import_tasks:
        file: tasks/install_neovim.yml
    - import_tasks:
        file: tasks/install_global.yml
    - import_tasks:
        file: tasks/install_delta.yml
    - import_tasks:
        file: tasks/install_cargotools.yml
    - import_tasks:
        file: tasks/install_safe.yml
    - import_tasks:
        file: tasks/install_rumt.yml
