- hosts: localhost
  connection: local
  tasks:
    - include_vars: vars/uneditable.yml
    - include_vars: vars/editable.yml
    - import_tasks:
        file: tasks/my_scripts.yml
    - import_tasks:
        file: tasks/install_pyenv.yml
    - import_tasks:
        file: tasks/install_pyenv_versions.yml
    - import_tasks:
        file: tasks/install_pipenv.yml
    - import_tasks:
        file: tasks/install_pylib.yml
