- hosts: localhost
  become: yes
  connection: local
  tasks:
    - include_vars: vars/editable.yml
    - include_vars: vars/uneditable.yml
    - include: tasks/my_scripts.yml
    - include: tasks/install_rust.yml
    - include: tasks/install_rust_nightly.yml
    - include: tasks/install_pyenv.yml
    - include: tasks/install_pyenv_versions.yml
    - include: tasks/install_pipenv.yml
    - include: tasks/install_golang.yml
    - include: tasks/install_exa.yml
    - include: tasks/install_ripgrep.yml
    - include: tasks/install_rusgit.yml
    - include: tasks/install_fd.yml
    - include: tasks/install_lf.yml
    - include: tasks/install_ghq.yml
    - include: tasks/install_fzf2nd.yml
    - include: tasks/install_neovim.yml
    - include: tasks/copy_sudoers.yml
