- hosts: localhost
  connection: local
  tasks:
    - include_vars: vars/uneditable.yml
    - include_vars: vars/editable.yml
    - import_tasks:
        file: tasks/apt_update_upgrade.yml
    - import_tasks:
        file: tasks/apt.yml
    - import_tasks:
        file: tasks/make_directories.yml
    - import_tasks:
        file: tasks/make_bashrc.yml
    - import_tasks:
        file: tasks/copy_files.yml
    - import_tasks:
        file: tasks/install_bashlibs.yml
