#!/usr/bin/env bash
set -eu
if [ "$UID" != "0" ] ;then
  echo "Require root privilege"
  exit 1
fi
./chikuwansible-playbook make_my_env_1.yml
./chikuwansible-playbook make_my_env_2.yml

echo PLEASE CHECK "/usr/bin/pip2" .
echo IF YOU DO NOT HAVE "/usr/bin/pip2" , YOU PROBABLY EXECUTE "sudo apt install python-pip" .
echo 'note: run "which pip2" .'
