#!/usr/bin/env bash
if [ "$UID" != "0" ] ;then
  echo "Require root privilege"
  exit 1
fi
if [ -e ./chikuwansible-playbook ] ;then
    ./chikuwansible-playbook ./remake_bash.yml
else
    echo "You can execute this command in chikuwansible directory"
fi

