#!/usr/bin/env bash
if [ "$UID" != "0" ] ;then
  echo "Require root privilege"
  exit 1
fi
if [ -e ./chikuwansible-playbook ] ;then
    ./chikuwasible-playbook ./remake_neovim.yml
else
    echo "You can execute this command in chikuwansible directory"
fi

