- hosts: localhost
  connection: local
  #become: yes
  #gather_facts: no
  tasks:
    - include_vars: vars/editable_others.yml
    - include_vars: vars/editable_ubuntu14.yml
      when: ansible_facts['distribution_major_version'] == "14"
    - include_vars: vars/editable_ubuntu16.yml
      when: ansible_facts['distribution_major_version'] == "16"
    - include_vars: vars/editable_ubuntu18.yml
      when: ansible_facts['distribution_major_version'] == "18"
    - include_vars: vars/editable_ubuntu20.yml
      when: ansible_facts['distribution_major_version'] == "20"
    - include_vars: vars/editable.yml
    - include_vars: vars/uneditable.yml
    #- name: Apt Update, Apt Upgrade
    #  include: tasks/apt_update_upgrade.yml
    - name: Remake Files For Bashrc
      include: tasks/remake_bash_files.yml
