- hosts: localhost
  connection: local
  #become: yes
  #gather_facts: no
  tasks:
    - include_vars: vars/editable.yml
    - include_vars: vars/uneditable.yml
    #- name: Apt Update, Apt Upgrade
    #  include: tasks/apt_update_upgrade.yml
    - name: Remake Files For Bashrc
      include: tasks/remake_bash_files.yml
    - name: Remake My Scripts
      include: tasks/my_scripts.yml
