[package]
name = "FILE_NAME"
version = "0.0.1"
authors = ["miyase256 <miyagaw61@gmail.com>"]

[dependencies]
#clap = "2.0"
clap = "*"
#colored = "1.6"
colored = "*"
#regex = "0.2"
regex = "*"
#serde_json = "1.0"
#chan = "0.1"
#chan-signal = "0.3"
lazy_static = "*"
