#!/usr/bin/env python3

from enert import *
import os
import re
this_file = os.path.basename(__file__)
r = re.compile(r""" \((\d+)\)""")

cmd = """ fd " \(\d+\)" """
files, _ = Shell(cmd).readlines()

for f in files:
    if f == this_file or f == 's' or f == 'desktop.ini':
        continue
    n = r.findall(f)
    if len(n) == 0:
        continue
    n = n[0]
    n = r.sub(f"_{n}", f)
    Shell(f'mv "{f}" "{n}"').call()
