- name: Install Basic Packages By Apt
  apt: "name={{item.name}}"
  with_items:
    - name: curl
    - name: gcc
    - name: make
    - name: cmake
    - name: perl
    - name: nasm
    - name: git
    - name: autoconf
    - name: binutils
    - name: lib32z1
    - name: libx32z1
    - name: libboost-all-dev
    - name: bison
    - name: flex
    - name: lib32z1-dev
    - name: libx32z1-dev
    - name: libbz2-dev
    - name: libtool
    - name: bsdmainutils
    - name: build-essential
    - name: module-assistant
    - name: libicu-dev
    - name: libpng-dev
    - name: libssl-dev
    - name: libbz2-dev
    - name: libreadline-dev
    - name: libsqlite3-dev
    - name: ucommon-utils
    - name: software-properties-common
    - name: clang
    - name: automake
    - name: socat
    - name: cifs-utils
    - name: openssh-server

- name: Install Basic Packages By Apt (ubuntu14)
  apt: "name={{item.name}}"
  with_items:
    - name: libtool
  when: ansible_facts['distribution_major_version'] == "14"

- name: Install Basic Packages By Apt (ubuntu20)
  apt: "name={{item.name}}"
  with_items:
    - name: libtool-bin
  when: ansible_facts['distribution_major_version'] == "20"

- name: Install Basic Packages By Apt (others)
  apt: "name={{item.name}}"
  with_items:
    - name: libtool-bin
  when: ansible_facts['distribution_major_version'] != "14" and ansible_facts['distribution_major_version'] != "20"

- name: Install LLVM By Apt
  apt: "name={{item.name}}"
  with_items:
    - name: llvm-{{llvm_version}}
    - name: libclang-{{llvm_version}}-dev

- name: Install GUI Packages By Apt (ubuntu14)
  apt: "name={{item.name}}"
  with_items:
    - name: libglfw2
    - name: libglfw-dev
  when: ansible_facts['distribution_major_version'] == "14"

- name: Install GUI Packages By Apt (ubuntu20, others)
  apt: "name={{item.name}}"
  with_items:
    - name: libglfw3
    - name: libglfw3-dev
  when: ansible_facts['distribution_major_version'] != "14"

- name: Install GUI Packages By Apt (common)
  apt: "name={{item.name}}"
  with_items:
    - name: xorg
    - name: xorg-dev
    - name: libfreetype6-dev
    - name: libglu1-mesa-dev
    - name: libgl1-mesa-glx
    - name: libglew-dev
    - name: freeglut3-dev
    - name: libsdl2-dev
    - name: libsdl2-ttf-dev
    - name: libsdl2-image-dev
    - name: libsdl2-mixer-dev

- name: Install Useful Tools By Apt (not ubuntu14)
  apt: "name={{item.name}}"
  with_items:
    - name: translate-shell
    - name: ffmpeg
  when: ansible_facts['distribution_major_version'] != "14"

- name: Install Useful Tools By Apt (common)
  apt: "name={{item.name}}"
  with_items:
    - name: traceroute
    - name: binwalk
    - name: gdb
    - name: gdbserver
    - name: ext4magic 
    - name: rsync
    - name: xclip
    - name: tree
    - name: imagemagick
    - name: ttyrec
    - name: x11-apps
    - name: xdotool
    - name: silversearcher-ag
    - name: desktop-file-utils
    - name: nmap
    - name: xsel
    - name: hping3
    - name: unar

- name: Get kernel Version
  shell: "uname -r"
  register: result
  changed_when: False
  failed_when: False

- name: Install Tools For Development Kernel By Apt
  apt: "name={{item.name}}"
  with_items:
    - name: "linux-headers-{{result.stdout}}"
    - name: libncurses5-dev
    - name: fakeroot
    - name: linux-headers-generic
    - name: ncurses-dev
    - name: libaio-dev
    - name: libsnappy-dev
    - name: liblzma-dev
    - name: zlib1g-dev
    - name: ccache
    - name: libelf-dev
