- name: apt install basic packages
  apt: "name={{item.name}}"
  with_items:
    - name: curl
    - name: gcc
    - name: make
    - name: cmake
    - name: perl
    - name: nasm
    - name: git
    - name: xorg
    - name: autoconf
    - name: binutils
    - name: lib32z1 libx32z1 lib64z1 lib64z1-dev
    - name: libboost-all-dev lib32z1-dev libx32z1-dev libbz2-dev
    - name: libtool
    - name: libtool-bin
    - name: bsdmainutils
    - name: build-essential
    - name: libicu-dev
    - name: libfreetype6-dev
    - name: libpng-dev
    - name: libssl-dev libbz2-dev libreadline-dev libsqlite3-dev
    - name: ucommon-utils
    - name: software-properties-common
    - name: llvm-{{llvm_version}}
    - name: libclang-{{llvm_version}}-dev
    - name: socat
    - name: cifs-utils
    - name: openssh-server

- name: apt install useful tools
  apt: "name={{item.name}}"
  with_items:
    - name: traceroute
    - name: binwalk
    - name: gdb
    - name: gdbserver
    - name: ext4magic 
    - name: rsync
    - name: xclip
    - name: tree
    - name: imagemagick ttyrec x11-apps xdotool
    - name: silversearcher-ag
    - name: desktop-file-utils
    - name: nmap

- name: apt install tools for kernel develop
  apt: "name={{item.name}}"
  with_items:
    - name: linux-headers-$(uname -r)
    - name: libncurses5-dev
    - name: fakeroot
    - name: linux-headers-generic
    - name: ncurses-dev
    - name: libaio-dev
    - name: libsnappy-dev
    - name: liblzma-dev
    - name: zlib1g-dev
