- name: Install Basic Packages By Apt
  apt:
    name: "{{item}}"
  with_items:
    - cmake
    - zlib1g-dev

- name: Install Exa By Cargo
  shell: "cargo install exa --force"
  become: no
  environment:
    PATH: "{{ansible_env.PATH}}:{{home}}/.cargo/bin"
