#- name: Install Python2
#  shell: bash -lc "pyenv install {{python2_pyenv_version}}"
#
#- name: Install Python3
#  shell: bash -lc "pyenv install {{python3_pyenv_version}}"

- name: Install Python2
  shell: "{{chikuwansible_path}}/install_python.sh {{pyenv_root}} {{python2_pyenv_version}}"
  args:
    chdir: "{{chikuwansible_path}}"
  become: no

- name: Install Python3
  shell: "{{chikuwansible_path}}/install_python.sh {{pyenv_root}} {{python3_pyenv_version}}"
  args:
    chdir: "{{chikuwansible_path}}"
  become: no

- name: Chown "pyenv_root"
  file:
    path: "{{pyenv_root}}"
    owner: "{{user}}"
    group: "{{user}}"
    recurse: yes

- name: Install Each Host Pip By Apt
  apt: "name={{item.name}}"
  with_items:
    - name: python-pip
    - name: python3-pip
