#- name: Install Python2
#  shell: bash -lc "pyenv install {{python2_pyenv_version}}"
#
#- name: Install Python3
#  shell: bash -lc "pyenv install {{python3_pyenv_version}}"

- name: "Chown {{user}}"
  file: "path={{pyenv_root}} owner={{user}} group={{user}}"
