- name: Install Basic Packages By Apt
  apt:
    name: "{{item}}"
  with_items:
    - cmake
    - zlib1g-dev

- name: Install Exa By Cargo
  become: yes
  become_user: "{{user}}"
  shell: bash -lc "cargo install exa --force"
  environment:
    PATH: "{{ansible_env.PATH}}:{{home}}/.cargo/bin"
