- name: Clone "pyenv"
  git: 
    repo: "https://{{git_token}}github.com/pyenv/pyenv.git"
    dest: "{{pyenv_root}}"
    force: yes

- name: Chown "pyenv_root"
  become: yes
  file:
    path: "{{pyenv_root}}"
    owner: "{{user}}"
    group: "{{user}}"
    recurse: yes

- name: Replace "#ANSIBLE_PYENV"
  replace:
    path: "{{bash_config_files}}/pyenv.sh"
    regexp: "#ANSIBLE_PYENV"
    replace: ""

- name: Install Basic Packages For "pip install"
  become: yes
  apt:
    name: "{{item}}"
    update_cache: yes
  with_items:
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev

#- name: "Install \"python{{python2_pyenv_version}}\""
#  shell: "{{chikuwansible_path}}/install_python.sh {{pyenv_root}} {{python2_pyenv_version}}"
#
#- name: "Install \"python{{python3_pyenv_version}}\""
#  shell: "{{chikuwansible_path}}/install_python.sh {{pyenv_root}} {{python3_pyenv_version}}"
#
#- name: Install pip3
#  apt:
#    name: python3-pip
