- name: "Add Apt-Repository \"python-{{python_version}}\""
  apt_repository: "repo=ppa:jonathonf/python-{{python_version}}"

- name: "Install \"python{{python_version}}\" \"python{{python_version}}-dev\" By Apt"
  apt: "name={{item.name}}"
  with_items:
    - name: "python{{python_version}}"
    - name: "python{{python_version}}-dev"

- name: Check Pip Version
  shell: pip --version
  register: pip_version_result
  changed_when: False

- name: Download "get-pip.py" (if you have no pip-3.6)
  get_url: "url=https://bootstrap.pypa.io/get-pip.py dest={{home}}/tmp"
  when: "'python 3.6' not in pip_version_result.stdout"

- name: Execute "get-pip.py" (if you have no pip-3.6)
  shell: "python{{python_version}} get-pip.py chdir={{home}}/tmp"
  when: "'python 3.6' not in pip_version_result.stdout"
