- name: Install Python2
  shell: "{{chikuwansible_path}}/install_python.sh {{pyenv_root}} {{python2_pyenv_version}}"
  args:
    chdir: "{{chikuwansible_path}}"
  become: no

- name: Chown "pyenv_root"
  file:
    path: "{{pyenv_root}}"
    owner: "{{user}}"
    group: "{{user}}"
    recurse: yes

- name: Install Python3
  shell: "{{chikuwansible_path}}/install_python.sh {{pyenv_root}} {{python3_pyenv_version}}"
  args:
    chdir: "{{chikuwansible_path}}"
  become: no

- name: Chown "pyenv_root"
  file:
    path: "{{pyenv_root}}"
    owner: "{{user}}"
    group: "{{user}}"
    recurse: yes

- name: Make "$pyenv_root/shims/python2,3"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{user}}"
    group: "{{user}}"
  with_items:
    - {src: "src_files/pyenv/templates/python2", dest: "{{pyenv_root}}/shims/python2"}
    - {src: "src_files/pyenv/templates/python3", dest: "{{pyenv_root}}/shims/python3"}

#
# ubuntu14~19
#

- name: Install Each Host Pip By Apt (ubntu14~19)
  apt: "name={{item.name}}"
  with_items:
    - name: python-pip
    - name: python3-pip
  when: ansible_facts['distribution_major_version'] < "20"

#
# ubuntu20
#

- name: Install Host Python2 By Apt (ubuntu20)
  apt: "name={{item.name}}"
  with_items:
    - name: python2
  when: ansible_facts['distribution_major_version'] == "20"

- name: Download Host Pip2 By Curl (ubuntu20)
  shell: "curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output /tmp/get-pip.py"
  when: ansible_facts['distribution_major_version'] == "20"

- name: Install Host Pip2 By Python2 (ubuntu20)
  shell: "{{host_python2_binary}} /tmp/get-pip.py"
  when: ansible_facts['distribution_major_version'] == "20"

- name: Install Host Pip3 By Apt (ubuntu20)
  apt: "name={{item.name}}"
  with_items:
    - name: python3-pip
  when: ansible_facts['distribution_major_version'] == "20"

- name: Move Host Pip2 from /usr/local/bin/ to /usr/bin/ (ubuntu20)
  shell: "mv /usr/local/bin/pip2 {{host_pip_dir}}"
  when: ansible_facts['distribution_major_version'] == "20"

- name: Move Host Pip2.7 from /usr/local/bin/ to /usr/bin/ (ubuntu20)
  shell: "mv /usr/local/bin/pip2.7 {{host_pip_dir}}"
  when: ansible_facts['distribution_major_version'] == "20"

- name: Move /usr/local/bin/pip to /usr/bin/pip.bak (ubuntu20)
  shell: "mv /usr/local/bin/pip {{host_pip_dir}}/pip.bak"
  when: ansible_facts['distribution_major_version'] == "20"
