- name: Clone "pyenv"
  git: 
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{home}}/.pyenv"

- name: Replace "#ANSIBLE_PYENV"
  replace:
    path: "{{bash_config_files}}/pyenv.sh"
    regexp: "#ANSIBLE_PYENV"
    replace: ""

- name: Source "bashrc"
  shell: 'export PYENV_ROOT="$HOME/.pyenv"; export PATH="$PYENV_ROOT/bin:$PATH"; eval "$(pyenv init -)"'

- name: Install Basic Packages For "pip install"
  apt:
    name: "{{item}}"
    update_cache: yes
  with_items:
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev

- name: "Install \"python{{python2_pyenv_version}}\""
  shell: "pyenv install {{python2_pyenv_version}}"

- name: "Install \"python{{python3_pyenv_version}}\""
  shell: "pyenv install {{python3_pyenv_version}}"
