- name: Install "lf" By Cargo
  shell: bash -lc "cargo install --git https://github.com/miyase256/lf --force"
  become: yes
  become_user: "{{user}}"
  environment:
    PATH: "{{ansible_env.PATH}}:{{home}}/.cargo/bin"
