- name: Install "rusgit" By Cargo
  shell: bash -lc "cargo install --git https://github.com/miyagaw61/rusgit --force"
  become: no
  environment:
    PATH: "{{ansible_env.PATH}}:{{home}}/.cargo/bin"

- name: Edit "bashrc" For Rusgit
  replace:
    path: "{{bash_config_files}}/aliases.sh"
    regexp: "# ANSIBLE_RUSGIT:"
    replace: ""
