- name: Switch python3
  shell: bash -lc "pyenv global {{python3_pyenv_version}}"

- name: Install "pipenv"
  shell: bash -lc "pip install pipenv"

- name: Replace "ANSIBLE_PIPENV"
  replace:
    path: "{{bash_config_files}}/pipenv.sh"
    regexp: "#ANSIBLE_PIPENV"
    replace: ""
