- name: Clone rumt
  git:
    repo: "https://{{git_token}}github.com/miyase256/rumt"
    dest: "{{my_repos}}/rumt"
    force: yes

- name: Move rumt binary to bin directory
  shell: "mv {{my_repos}}/rumt/rumt {{binaries}}/rumt"

