- name: Install cargo-edit
  shell: bash -lc "cargo install cargo-edit"
  become: no
  environment:
    PATH: "{{ansible_env.PATH}}:{{home}}/.cargo/bin"

- name: Install cargo-watch
  shell: bash -lc "cargo install cargo-watch"
  become: no
  environment:
    PATH: "{{ansible_env.PATH}}:{{home}}/.cargo/bin"

- name: Install rusty-tags
  shell: bash -lc "cargo install rusty-tags"
  become: no
  environment:
    PATH: "{{ansible_env.PATH}}:{{home}}/.cargo/bin"

- name: Copy config.toml of rusty-tags
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{user}}"
    group: "{{user}}"
  with_items:
    - {src: "src_files/rusty-tags/config.toml", dest: "{{home}}/.rusty-tags/config.toml"}
