#- name: Add Apt-Repository For NeoVim
#  apt_repository: repo=ppa:neovim-ppa/unstable
#
#- name: Apt Update
#  apt: update_cache=yes

- name: Install Basic Packages For NeoVim By Apt
  apt: 
    name: software-properties-common 
  become: yes

- name: Install NeoVim By Apt
  apt: 
    name: neovim
  become: yes

- name: Update NeoVim By Pip
  shell: bash -lc "{{host_python3_pip}} install -U neovim"

- name: Install Packages For NeoVim's Plugins By Apt
  apt:
    name: "{{item.name}}"
  become: yes
  with_items:
    - name: silversearcher-ag
    - name: "llvm-{{llvm_version}}"
    - name: "clang-{{llvm_version}}"

- name: Switch python3
  shell: bash -lc "pyenv global {{python3_pyenv_version}}"

- name: Install pynvim
  shell: bash -lc "python -m pip install -U pynvim"

- name: Install neovim-remote
  shell: bash -lc "python -m pip install -U neovim-remote"

- name: Chown "/usr/local/lib/"
  become: yes
  file:
    path: "/usr/local/lib/"
    owner: "{{user}}"
    group: "{{user}}"
    recurse: yes

- name: Install pynvim to /usr/bin/python2
  shell: bash -lc "/usr/bin/python2 -m pip install -U pynvim"

- name: Make Directories For NeoVim
  file:
    path: "{{item.path}}"
    state: directory
    owner: "{{user}}"
    group: "{{user}}"
  with_items:
    - path: "{{nvim_config_files}}"
    - path: "{{nvim_config_files}}/.cache"

- name: Copy Files For NeoVim
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{user}}"
    group: "{{user}}"
  with_items:
    - {src: src_files/nvim/init, dest: "{{nvim_config_files}}"}
    - {src: src_files/nvim/plugins, dest: "{{nvim_config_files}}"}

- name: Make Files From Templates For NeoVim
  template: 
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{user}}"
    group: "{{user}}"
  with_items:
    - {src: "src_files/nvim/templates/init.vim", dest: "{{nvim_config_files}}/init.vim"}
    - {src: "src_files/nvim/templates/dein_trigger.vim", dest: "{{nvim_config_files}}/plugins/dein_trigger.vim"}
    - {src: "src_files/nvim/templates/lazy.toml", dest: "{{nvim_config_files}}/plugins/lazy.toml"}
    - {src: "src_files/nvim/templates/let.vim", dest: "{{nvim_config_files}}/init/let.vim"}
    - {src: "src_files/nvim/templates/set.vim", dest: "{{nvim_config_files}}/init/set.vim"}

- name: Replace ANSIBLE_BRACE
  replace:
    dest: "{{nvim_config_files}}/plugins/lazy.toml"
    regexp: ANSIBLE_BRACE 
    replace: "{"

- name: Clone DEIN Repository
  git:
    repo: "https://{{git_token}}github.com/Shougo/dein.vim"
    dest: "{{nvim_config_files}}/repos/github.com/Shougo/dein.vim"
    force: yes

- name: Chown "nvim"
  become: yes
  file:
    path: "{{nvim_config_files}}"
    owner: "{{user}}"
    group: "{{user}}"
    recurse: yes
