- name: Install Old Golang By Apt
  apt:
    name: "golang-1.9-go"

- name: Install Latest Golang
  shell: "/usr/lib/go-1.9/bin/go get golang.org/dl/go{{golang_version}}"
  become: no

- name: Install Latest Golang
  shell: "{{home}}/go/bin/go{{golang_version}} download"
  become: no

- name: "Make Go Symbolic Link"
  file:
    path: /usr/local/bin/go
    src: "{{home}}/go/bin/go{{golang_version}}"
    state: link
