- name: Add Apt-Repository For NeoVim
  apt_repository: repo=ppa:neovim-ppa/unstable

- name: Apt Update
  apt: update_cache=yes

- name: Install Basic Packages For NeoVim By Apt
  apt: 
    name: software-properties-common 

- name: Install NeoVim By Apt
  apt: 
    name: neovim

- name: Update NeoVim By Pip
  shell: bash -lc "pip install -U neovim"

- name: Install Packages For NeoVim's Plugins By Apt
  apt:
    name: "{{item.name}}"
  with_items:
    - name: silversearcher-ag
    - name: "llvm-{{llvm_version}}"
    - name: "clang-{{llvm_version}}"

- name: Install Packages For NeoVim's Plugins By Pip
  shell: bash -lc "pip install neovim-remote"

- name: Make Directories For NeoVim
  file:
    path: "{{item.path}}"
    state: directory
    owner: "{{user}}"
    group: "{{user}}"
  with_items:
    - path: "{{nvim_config_files}}"
    - path: "{{nvim_config_files}}/.cache"

- name: Copy Files For NeoVim
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{user}}"
    group: "{{user}}"
  with_items:
    - {src: src_files/nvim/init, dest: "{{nvim_config_files}}"}
    - {src: src_files/nvim/plugins, dest: "{{nvim_config_files}}"}

- name: Make Files From Templates For NeoVim
  template: 
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{user}}"
    group: "{{user}}"
  with_items:
    - {src: "src_files/nvim/templates/init.vim", dest: "{{nvim_config_files}}/init.vim"}
    - {src: "src_files/nvim/templates/dein_trigger.vim", dest: "{{nvim_config_files}}/plugins/dein_trigger.vim"}
    - {src: "src_files/nvim/templates/lazy.toml", dest: "{{nvim_config_files}}/plugins/lazy.toml"}
    - {src: "src_files/nvim/templates/let.vim", dest: "{{nvim_config_files}}/init/let.vim"}

- name: Replace ANSIBLE_BRACE
  replace:
    dest: "{{nvim_config_files}}/plugins/lazy.toml"
    regexp: ANSIBLE_BRACE 
    replace: "{"

- name: Clone DEIN Repository
  git:
    repo: https://github.com/Shougo/dein.vim
    dest: "{{nvim_config_files}}/repos/github.com/Shougo/dein.vim"

- name: Chown "nvim"
  file:
    path: "{{nvim_config_files}}"
    owner: "{{user}}"
    group: "{{user}}"
    recurse: yes
