- name: Make Basic Directories
  file:
    path: "{{item.path}}"
    state: directory
    owner: "{{user}}"
    group: "{{user}}"
  with_items:
    - path: "{{tmp}}"
    - path: "{{docs}}"
    - path: "{{events}}"
    - path: "{{program}}"
    - path: "{{config_files}}"
    - path: "{{binaries}}"
    - path: "{{vimbackup}}"
    - path: "{{nvim_logfile_dir}}"

- name: Change mode of cache directory
  file:
    path: "{{home}}/.cache"
    owner: "{{user}}"
    group: "{{user}}"
    mode: "u=rwx,g=rwx,o=rwx"
    recurse: yes
