- name: Make Basic Directories
  file:
    path: "{{item.path}}"
    state: directory
    owner: "{{user}}"
    group: "{{user}}"
  with_items:
    - path: "{{tmp}}"
    - path: "{{docs}}"
    - path: "{{events}}"
    - path: "{{program_files}}"
    - path: "{{config_files}}"
