- name: Copy My Python Scripts
  copy:
    src: "src_files/python/{{item.name}}"
    dest: "{{binaries}}/{{item.name}}"
    owner: "{{user}}"
    group: "{{user}}"
    mode: "u=rwx,g=rwx,o=rwx"
  with_items:
    - name: download
    - name: rall
    - name: tmp.py
    - name: numfile_fmt
