- name: Copy My Scripts
  copy:
    src: "src_files/scripts/{{item.name}}"
    dest: "{{binaries}}/{{item.name}}"
    owner: "{{user}}"
    group: "{{user}}"
    mode: "u=rwx,g=rwx,o=rwx"
  with_items:
    - name: download
    - name: rall
    - name: tmp.py
    - name: numfile_fmt
    - name: lszip
    - name: backup
    - name: l2w
    - name: w2l
    - name: gettag
    - name: fil
    - name: procon_ready
    - name: get_tag_from_commit
    - name: git_sn
    - name: gettag
    - name: op
    - name: start
    - name: follow_upstream
