- name: Copy Files For NeoVim
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{user}}"
    group: "{{user}}"
  with_items:
    - {src: src_files/nvim/init, dest: "{{nvim_config_files}}"}
    - {src: src_files/nvim/plugins, dest: "{{nvim_config_files}}"}

- name: Make Files From Templates For NeoVim
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{user}}"
    group: "{{user}}"
  with_items:
    - {src: "src_files/nvim/templates/init.vim", dest: "{{nvim_config_files}}/init.vim"}
    - {src: "src_files/nvim/templates/dein_trigger.vim", dest: "{{nvim_config_files}}/plugins/dein_trigger.vim"}
    - {src: "src_files/nvim/templates/lazy.toml", dest: "{{nvim_config_files}}/plugins/lazy.toml"}
    - {src: "src_files/nvim/templates/let.vim", dest: "{{nvim_config_files}}/init/let.vim"}

- name: Replace ANSIBLE_BRACE
  replace:
    dest: "{{nvim_config_files}}/plugins/lazy.toml"
    regexp: ANSIBLE_BRACE
    replace: "{"
