#!/bin/bash

THIS_DIR=$PWD

onerror() {
    set +x
    status=$?
    script=$0
    if [ ! -e $script ] ;then
        script=${THIS_DIR}/$script
    fi
    line=$1
    shift

    args=
    for i in "$@"; do
        args+="\"$i\" "
    done

    echo ""
    echo "------------------------------------------------------------"
    echo "Error occured on $script [Line $line]: Status $status"
    echo -n " >> "
    cat $script | head -n $line | tail -n $(($line - $line + 1))
    echo ""
    echo "PID: $$"
    echo "User: $USER"
    echo "Current directory: $PWD"
    echo "Command line: $script $args"
    echo "------------------------------------------------------------"
    echo ""

    date
    python $HOME/src/github.com/miyagi1024/miyagi1024_linebot/push.py $MY_LINE_ID 'error occured.'
}

begintrap() {
    set -e
    trap 'onerror $LINENO  "$@"' ERR
}

begintrap

rsyncrm() {
    source $HOME/bin/error_trap.sh
    echo "[+]save: ${2}"
    diff -r ${1} ${2} | grep "Only in ${2}" | sed -E 's@Only in ([^:]*): (.*)@\1/\2@g' > /tmp/will_delete_files
    if [ "$(cat /tmp/will_delete_files)" ] ;then
        cat /tmp/will_delete_files | while read line ;do
            dname=$(dirname "$line")
            dname=$(echo $dname | sed -E "s@${2}@${2}_grave@g")
            bname="$(basename "${line}")"
            if [ ! -e "$dname" ] ;then
                mkdir -p "$dname"
            fi
            #if [ ! -e "$dname/$bname" ] ;then
            #    mkdir -p "$dname/$bname"
            #fi
            echo "copy: to $dname/$bname"
            cp -a "$line" "$dname/$bname"
        done
    fi
    echo "[+]rsync: ${1}/ ${2}"
    rsync -a --delete ${1}/ ${2}
}

backup_fn() {
    source $HOME/bin/error_trap.sh
    dst_dir=$1
    if [ ! -e ${home2}/${dst_dir} ] ;then
        mkdir ${home2}/${dst_dir}
    fi
    if [ ! -e ${home2}/${dst_dir}_grave ] ;then
        mkdir ${home2}/${dst_dir}_grave
    fi
    rsyncrm ${home1}/${dst_dir}/ ${home2}/${dst_dir}
}

if [ $# -eq 2 ] ;then
    home1=$1
    home2=$2

    if [ ! -e $1 ] ;then
        echo "[!]ERROR"
        exit
    fi
    if [ ! -e $2 ] ;then
        echo "[!]ERROR"
        exit
    fi

    date

    backup_fn bin
    backup_fn src
    backup_fn docs
    #backup_fn program
    #backup_fn tmp
    backup_fn large_docs/ctf
    backup_fn large_docs/games
    backup_fn large_docs/images
    backup_fn large_docs/iso
    backup_fn large_docs/videos
    #backup_fn large_docs/VMs

    date
    python $HOME/src/github.com/miyagi1024/miyagi1024_linebot/push.py $MY_LINE_ID 'backup finished.'
else
    echo "backup <src home directory> <dest home directory>"
fi
