#!/usr/bin/env python3

from enert import *
import sys
from googletrans import Translator

argv = sys.argv
argc = len(argv)

src_text = " ".join(argv[1:])
#cmd = f"trans en:ja \"{src_text}\""
#translated_data, _ = Shell(cmd).readlines()
#print(translated_data)

print(src_text)
translator = Translator()
translated_data = translator.translate("Hello everyone.", dest="ja")
print(translated_data)
