#!/usr/bin/env python3
from enert import *
import sys

argv = sys.argv[1:]
argc = len(argv)

if not argc > 0:
    print("Usage: get_tag_from_commit.py TAG_NAME [FILE_NAME] COMMIT_ID")
    exit(0)
if argv[0] == "-h":
    print("Usage: get_tag_from_commit.py TAG_NAME [FILE_NAME] COMMIT_ID")
    exit(0)

if argc == 3:
    tag_name = argv[0]
    file_name = argv[1]
    commit_id = argv[2]
elif argc == 2:
    tag_name = argv[0]
    commit_id = argv[1]
else:
    print("Usage: get_tag_from_commit.py TAG_NAME [FILE_NAME] COMMIT_ID")
    exit(0)

tags, _ = Shell("git tag").readlines()
tags.reverse()
start = 0;
for i in range(0, len(tags)):
    if not tags[i] == tag_name:
        continue
    else:
        start = i
        break
for i in range(start, len(tags)):
    if argc == 3:
        output, _ = Shell("git log {0}..{1} -- {2} | rg {3}".format(tags[i+1], tags[i], file_name, commit_id)).read()
    elif argc == 2:
        output, _ = Shell("git log {0}..{1} | rg {2}".format(tags[i+1], tags[i], commit_id)).read()
    else:
        print("Usage: get_tag_from_commit.py TAG_NAME [FILE_NAME] COMMIT_ID")
        exit(0)
    print("[+]{0}..{1}:".format(tags[i+1], tags[i]))
    if output:
        print(output)
        break
