#!/usr/bin/env python3
from enert import *
import sys

argv = sys.argv[1:]
argc = len(argv)

if argc != 1 or argv[0] == "-h":
    print("Usage: m <r|b>")
    exit()

f = File("./Mfile")
if not f.exist():
    f = File("../Mfile")
if not f.exist():
    print("Mfile: not found")
    exit()
lines = f.readlines()
run_codes = []
build_codes = []
build_idx = -1
for i, line in enumerate(lines):
    if not line == "":
        run_codes.append(line)
        continue
    else:
        build_idx = i
        break
build_codes = lines[build_idx+1:]
if argv[0] == "r":
    for code in run_codes:
        Shell(code).call()
elif argv[0] == "b":
    for code in build_codes:
        Shell(code).call()
