#!/usr/bin/env python3

from enert import *
import os
import re
import sys
this_file = os.path.basename(__file__)

#r = re.compile(r"""\((\d+)\)""")
r = re.compile(r""" \((\d+)\)""")

#cmd = """ fd "\(\d+\)" """
cmd = """ fd " \(\d+\)" """

def usage():
    print("Usage: numfile_fmt")
    exit()

if get(sys.argv, 1) == "-h":
    usage()

files, _ = Shell(cmd).readlines()

for f in files:
    if f == this_file or f == 's' or f == 'desktop.ini':
        continue
    num = r.findall(f)
    if len(num) == 0:
        continue
    num = num[0]
    n = r.sub(f"_{num}", f)
    if File(n).exist():
        num = int(num)
        while True:
            num = num + 1
            if num == 100:
                print(f + ": over 100")
                break
            n = r.sub(f"_{num}", f)
            if File(n).exist():
                continue
            Shell(f'mv "{f}" "{n}"').call()
            break
        continue
    else:
        Shell(f'mv "{f}" "{n}"').call()
