#!/usr/bin/env python

from enert import *

def usage():
    print("ratecalc <start> <end>")

def ratecalc(start, end):
    rate = (1-(start/end))*100
    return rate

argv = sys.argv
arg1 = get(argv, 1)
arg2 = get(argv, 2)

if (arg1 == None or arg2 == None or arg1 == "-h"):
    usage()
    exit()

arg1 = arg1.replace(",", "")
arg2 = arg2.replace(",", "")
arg1 = float(arg1)
arg2 = float(arg2)

rate = ratecalc(arg1, arg2)
print(rate)
