#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x

program="${0##*/}"
if [[ "$program" = "python"* ]]; then
  for arg; do
    case "$arg" in
    -c* | -- ) break ;;
    */* )
      if [ -f "$arg" ]; then
        export PYENV_FILE_ARG="$arg"
        break
      fi
      ;;
    esac
  done
fi

export PYENV_ROOT="/home/miyase256/docs/config_files/.pyenv"
if test "$(cat $PYENV_ROOT/version | grep 2.7.15)" ;then
    exec "/usr/bin/python3" "$@"
else
    exec "/home/miyase256/docs/config_files/.pyenv/libexec/pyenv" exec "$program" "$@"
fi
